language: swift # or objective-c
osx_image: xcode8.3
script:
  - xcodebuild -scheme BasketPrice -workspace BasketPrice.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.3.1'  -configuration Debug -enableCodeCoverage YES build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BasketPrice'