language: swift # or objective-c
osx_image: xcode8.3
script:
  - xcodebuild -scheme BasketPrice -project BasketPrice.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 5,OS=10'  -configuration Debug -enableCodeCoverage YES build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'BasketPrice'